const levelMaps = [
  [     "x                                                    ",
        "x             x                                          ",
        "x            x                                         ",
        "x             x                               r         ",
        "x             x                               @          ",
        "x             x                                         ",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x      gggggg x",
        "xxxxxxxxxxxxxxx",
]

  // [     "xxxxxxxxxxxxxxx                                                    ",
  //       "x             x                                          ",
  //       "x   i         x                                         ",
  //       "x             x                               r         ",
  //       "x             x                               @          ",
  //       "x             x                                         ",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x         1   x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x         a   x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x         2   x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x             x",
  //       "x         !   x",
  //       "xxxxxxxxxxxxxxx"
  //     ],
  //     [
  //       "                                                                ",
  //       "                      ",   
  //       "                     ",
  //       " x                                x          x",
  //       " x                                x          x",
  //       " x                                x          x ",
  //       " x                                x          x         x",
  //       " x                              ! x          x         x",
  //       " x                                x          x         x",
  //       " x   3                       4    x          x         x",
  //       " x                              x x          x         x",
  //       " x i                              xxxxxxxxxxxx      r  x",
  //       " x                              @                      x",    
  //       " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  //     ],
      //  [  "                                                        ",
      //     " x                                                     x",   
      //     " x                                                     x",
      //     " x                                                     x",
      //     " x                                                     x",
      //     " x                                                     x",
      //     " x                       ! @                           x",
      //     " x                  xxxxxxxxxxxx                       x",
      //     " x                  xxxxxxxxxxxx                       x",
      //     " x   5           xxxxxxxxxxxxxxxxxx                    x",
      //     " x               xxxxxxxxxxxxxxxxxx                    x",
      //     " x i          xxxxxxxxxxxxxxxxxxxxxxxx              r  x",
      //     " x            xxxxxxxxxxxxxxxxxxxxxxxx                 x",    
      //     " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      //   ],

    //   [   "x         @   x",
    //       "x    !        x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x             x",
    //       "x    i    r   x",
    //       "x             x",
    //       "xxxxxxxxxxxxxxx"
    // ]
  ];
    
    
export default levelMaps;