const levelMaps = [

  [   "xxxxxxxxxxxxxxx                              v    xxxxx            ",
  "x             x                 |                                 =",
  "x   i r        x                                                  ",
  "x                                               xxxxx            ",
  "x                                                               ",
  "x                                           !      ",
  "xxxxxxxxxxxxxxxxxwwwwwwwpppppppxxxxtxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]];


    // [   "xxxxxxxxxxxxxxx                                  xxxxx            ",
    //     "x             x                                    r              ",
    //     "x   i         x                                    @              ",
    //     "x             x                                  xxxxx            ",
    //     "x             x                                    3              ",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x         1   x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x        2    x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x             x",
    //     "x         !   x",
    //     "xxxxxxxxxxxxxxx"
    //   ],
    //   [
    //     "                                                                ",
    //     "                      ",   
    //     "                     ",
    //     " x                   ",
    //     " x                     ",
    //     " x                                           ",
    //     " x                                x          x         x",
    //     " x                                x          x         x",
    //     " x                              ! x          x         x",
    //     " x                      4         x          x         x",
    //     " x                                x          x         x",
    //     " x i                              xxxxxxxxxxxx      r  x",
    //     " x                                                     x",    
    //     " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    //     "      ",
    //     "       ",
    //     "                      "
    //   ],
      //     "                                                                ",
      //     " x                                                     x",   
      //     " x                                                     x",
      //     " x                                                     x",
      //     " x                      t                              x",
      //     " x                                                     x",
      //     " x                           t                         x",
      //     " x                    t                                x",
      //     " x                                                     x",
      //     " x               xxxxxxxxxxxxxxxxxx                    x",
      //     " x              xxxxxxxxxxxxxxxxxxxx                   x",
      //     " x i           xxxxxxxxxxxxxxxxxxxxxx               r  x",
      //     " x            xxxxxxxxxxxxxxxxxxxxxxxx                 x",    
      //     " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      //     "      ",
      //     "       ",
      //     "                      "
      //   ],
      // [   "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x             x",
      //     "x    i    r   x",
      //     "x             x",
      //     "xxxxxxxxxxxxxxx"
    // ];
    
    
export default levelMaps;