const levelMaps = [
    [   "xxxxxxxxxxxxxxx",
        "x             x",
        "x   i         x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x         1   x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x        2    x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x         !   x",
        "xxxxxxxxxxxxxxx"
      ],
      [
        "                      ",
        "                      ",   
        "                     ",
        "                     ",
        "                      ",
        "                     ",
        "                      ",
        "                     ",
        "                      ",
        "                      ",
        " x              =x  ",
        " x ir             x  ",
        " x         !  xxx  ",
        " xxxxx   xx    =x  ",
        "     xxxxxxxxxxxxxx  ",
        "     xxxxxxxxxxxxxx  ",
        "                      "
      ]];
    
    
export default levelMaps;